### ISSUE TITLE
Transfer TiKV Dev Guide Repo to tikv org

### ISSUE THREAD

**Issue by tisonkun** [tikv/community#163]
[Proposal: TiKV Development Guide](https://internals.tidb.io/t/topic/277) was posted at 2021-07-21, and during the last half year we finished several chapter of the guide at https://github.com/tisonkun/tikv-dev-guide.

However, there're still 36 outstanding issues and thus at least 36 sections to be written. After a discussion with @zz-jason, he proposed that we can transfer the dev guide to tikv org and proceed the work.

I'm glad to see any pull requests to fulfill new sections, and don't insist on what owner the repo belongs to. The important thing, from my side, is the content itself. If transferring the repo to tikv org can help moving forward the progress, I'm willing to do so.

So here is the issue to discuss about such a transfer. Looking forward to responses.

For achieving the transfer, I think I have all required permission to do it.

**Comment by pingyu** [comment]
+1.

Quite agree with the importance of the Dev Guide. As I'm also a newbie, I think writing or revising a related chapter when finished learning a module will help me to get a better understanding. And the chapter will also help more people to know about TiKV. When they go on revising with latest codebase, we will get a positive cycle. I am quite look forward this will happen.

**Comment by tisonkun** [comment]
@zz-jason so what's the process? IMO to introduce a new repo of tikv org, we should either consult to tikv maintainers for consensus. I may create a pull request with vote content in this week.

**Comment by zz-jason** [comment]
@tikv/maintainers could you help to take a look at this issue, maybe we can shorten the process, directly open the new repo.

**Comment by BusyJay** [comment]
LGTM

**Comment by tisonkun** [comment]
I'll create the PR now.

**Comment by tisonkun** [comment]
Closed by #164. You can find the guide repo at https://github.com/tikv/tikv-dev-guide.
