### ISSUE TITLE
Transfer `components/match_template` to tikv org 

### ISSUE THREAD

**Issue by andylokandy** [tikv/community#181]
[match_template](https://github.com/tikv/tikv/tree/master/components/match_template) is a procedural macro that generates repeated match arms by pattern, which is almost the only way to dispatch code path to static types depending on a runtime value. Since it's general enough, I propose to move it to TiKV org and then publish it to crates.io so that the rust community could be benifit from it.

**Comment by BusyJay** [comment]
+1

**Comment by BusyJay** [comment]
I think a standalone repository is better since it hardly changes. Messing with a large code repository doesn't feel good to me.

**Comment by tisonkun** [comment]
@andylokandy you may already have the privilege to create the repo and set up. I'm unsure whether the vote progress still works and if you don't mind, you can create a pull request to formally meet a consensus.

**Comment by andylokandy** [comment]
Unfortunately, I don't have that privilege, maybe @sunxiaoguang can help.

**Comment by tisonkun** [comment]
FYI - repo setup at https://github.com/tikv/match-template/ and I publish the crate at https://crates.io/crates/match-template, as well as add @tikv/tikv-maintainers as its owner. @BusyJay @andylokandy you may update the tikv part and I'm glad to know if Databend or other project use this crate also.

**Comment by BusyJay** [comment]
Cool! Just a hint, if using `git filter-branch` to extract the subdirectory/component, we can retain all the related history.

**Comment by tisonkun** [comment]
@BusyJay I forgot this topic XD
