### ISSUE TITLE
Update governance document

### ISSUE THREAD

**Issue by sunxiaoguang** [tikv/community#207]
Due to the fact that the governance document has been outdated for some time. I hereby propose a refresh of governance document according to the new affiliations of steering committee members and infra members.

The changes are:
* Clear steering committee member Jay Li's affiliation based on his own preference.
* Replace infra members, Zili Chen and Qiang Zhou, to Junchen Ye and Wuhui Zuo.

Please make comments if you have any concern, thanks

**Comment by winkyao** [comment]
+1
